# Site settings
title: Marcelo Boeira
author: Marcelo Boeira
email: me@marceloboeira.com
description: "Marcelo Boeira's blog, weird thoughts about software development, electronic engineering."
baseurl: ""
url: ""
facebook_username: b03ir4
twitter_username: b03ir4
github_username:  marceloboeira
bitbucket_username:  marceloboeira
instagram_username:  marceloboeirajr

gravatar_url:	"http://api.vimia.cc/gravatar/?email=marceloboeira@live.com&size=100"

# Build settings
markdown: kramdown
permalink: "/:year/:title.post"
paginate_path: "/page:num"